config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'
  get '/admin', to: 'static_pages#admin'
  get '/test_payment', to: 'static_pages#test_payment'
  get '/news', to: 'static_pages#news'
  get '/users_index_adm', to: 'static_pages#users_index_adm'
  get 'user_adm/:id', to: 'static_pages#user_adm'

  resources :products
  get '/main', to: 'products#index_main'
  get '/foodtrack', to: 'products#index_foodtrack'
  get '/delivery', to: 'products#index_delivery'
  get '/delivery_products', to: 'products#index_delivery_products'
  get '/products_index_adm', to: 'products#index_adm'

  resources :poster_clients, only: [:new, :create, :edit, :update]
  get '/poster_info', to: 'poster_clients#poster_info'
  get '/bonus_info', to: 'poster_clients#bonus_info'
  get '/coupon', to: 'poster_clients#coupon'

  resources :poster_admin, only: [:index]
  post '/update_clients_bonus', to: 'poster_admin#update_clients_bonus'
  post '/update_poster_products', to: 'poster_admin#update_poster_products'

  # Yandex.Kassa
  post '/order_check', to: 'yandex_kassa#order_check'
  post '/order_payment_aviso', to: 'yandex_kassa#order_payment_aviso'
  get '/order_fail', to: 'yandex_kassa#order_fail'
  get '/order_success', to: 'yandex_kassa#order_success'

  # Shopping Cart
  resources :order_items, only: [:create, :update, :destroy]
  get '/cart', to: 'orders#cart'
  get '/order_placed', to: 'orders#order_placed'
  # get '/card_pay', to: 'orders#card_pay'
  resources :orders, only: [:update, :index, :show ]
  get "card_pay/:id", :controller => "orders", :action => "card_pay"
  get '/orders_index_adm', to: 'orders#index_adm'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'application_home', only: [:home]
  before_action :authenticate_admin, only: [:admin, :users_index_adm, :user_adm]
  
  def home
  end

  def news
  end

  def test_payment
  	@yandex_kassa_scid = ENV["yandex_kassa_scid"].to_s
  end

  # ADMIN actions
  def admin
  end

  def users_index_adm
    @users = User.all
  end

  def user_adm
    @user = User.find_by_id(params[:id])
  end

end

app/views/static_pages/admin.html.erb
<% provide(:breadcrumb, "Админка") %>
<h2>Панель администратора сайта</h2>
<ul>
	<li><%= link_to "Список товаров", products_index_adm_path %></li>
	<li><%= link_to "Админка интеграции с Poster", poster_admin_index_path %></li>
	<li><%= link_to "Список заказов", orders_index_adm_path %></li>
	<li><%= link_to "Просмотр списка пользователей", users_index_adm_path %></li>
	<li><%= link_to "Настройка SEO (пока не доступен)", '#' %></li>
</ul>

app/views/static_pages/news.html.erb
<!-- Page Content-->
<main class="page-content">
  <section class="section-top-0 section-bottom-80 section-lg-top-40 bg-images-7 section-md-bottom-115">
    <div class="shell">
      <div class="range">
        <div class="cell-md-9 cell-md-preffix-3 text-center text-md-left news_block">
          <h3>Последние новости</h3>
          <div class="range divider-bottom offset-top-37 section-md-bottom-47 news_block_div">
            <div class="cell-md-7">
              <time datetime="2017-01-01" class="h5 news_block_time">1 янв 2017</time>
              <h5 class="news_block_title"><a href="#">С Новым годом!</a></h5>
              <p class="offset-top-30 news_block_desc">Уважаемые гости нашего кафе. Поздравляем вас с Новым 2017 годом. К новому году у нас обновилось меню. Ждем вас :)</p>
            </div>
            <div class="cell-md-5 img-wraper-2">
              <%= image_tag("events-03.jpg", class: "img-responsive margin-center", alt: "") %>
            </div>
          </div>
          <div class="range offset-top-45 divider-bottom section-md-bottom-47 news_block_div">
            <div class="cell-md-7">
              <time datetime="2016-12-22" class="h5 news_block_time">22 дек 2016</time>
              <h5 class="news_block_title"><a href="#">Зимнее меню</a></h5>
              <p class="offset-top-30 news_block_desc">С 22 декабря у нас новое зимнее меню. Новые виды бургеров, закусок и обновленный ассортимент кофе и напитков!</p>
            </div>
            <div class="cell-md-5 img-wraper-2">
              <%= image_tag("events-04.jpg", class: "img-responsive margin-center", alt: "") %>
            </div>
          </div>
          <div class="range offset-top-45 news_block_div">
            <div class="cell-md-7">
              <time datetime="2016-12-01" class="h5 news_block_time">1 дек 2016</time>
              <h5 class="news_block_title"><a href="#">Акция скидки 30%</a></h5>
              <p class="offset-top-30 news_block_desc">12 декабря акация скидки 30% на все напитки. Приходите, для получения скидки кодовое слово MITRO12</p>
            </div>
            <div class="cell-md-5 img-wraper-2">
              <%= image_tag("events-05.jpg", class: "img-responsive margin-center", alt: "") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>

app/views/static_pages/test_payment.html.erb
<% provide(:breadcrumb, "Test Payment") %>
<h2>Страница для тестирования интеграции с Яндекс.Кассой</h2>
<form action="https://demomoney.yandex.ru/eshop.xml" method="POST">
<input name="shopId" value="88596" type="hidden">
<input name="scid" value="<%= @yandex_kassa_scid %>" type="hidden">
<input name="customerNumber" value="Buyer01"><!-- Идентификатор вашего покупателя -->
<input name="sum" value="1.11"><!-- Сумма покупки (руб.) -->
<input type="submit" value="Оплатить">
</form>

app/views/static_pages/user_adm.html.erb
<% provide(:breadcrumb, "Админка / Просмотр пользователя") %>
<div>
	<h2>Просмотр пользователя</h2>
	<div class="form-group">
		<a class="btn btn-default" href="/admin">В админку</a>
		<%= link_to "Список пользователей", '/users_index_adm', class: "btn btn-default" %>
	</div>
	<div><%= User.human_attribute_name("id") %>: 
		<b><%=@user.id %></b>
	</div>
	<div><%= User.human_attribute_name("created_at") %>: 
		<b><%= @user.created_at.strftime('%d.%m.%Y %T') %></b>
	</div>
	<div><%= User.human_attribute_name("email") %>: 
		<b><%= @user.email %></b>
	</div>
	<div><%= User.human_attribute_name("is_admin") %>: 
		<b><%= @user.is_admin ? "Да" : "Нет" %></b>
	</div>
	<div><%= User.human_attribute_name("last_sign_in_at") %>: 
		<b><%= @user.last_sign_in_at.strftime('%d.%m.%Y %T') %></b>
	</div>
	<div>Клиент постера: 
		<b><%= @user.poster_client ? "Да" : "Нет" %></b>
	</div>
	<br/>
	<h4>Информация по клиенту Постера</h4>
	<div><%= PosterClient.human_attribute_name("client_name") %>: 
		<b><%= @user.poster_client&.client_name %></b>
	</div>
	<div><%= PosterClient.human_attribute_name("is_active") %>: 
		<b><%= @user.poster_client&.is_active %></b>
	</div>
	<div><%= PosterClient.human_attribute_name("poster_client_id") %>: 
		<b><%= @user.poster_client&.poster_client_id %></b>
	</div>
	<div><%= PosterClient.human_attribute_name("client_sex") %>: 
		<b><%= @user.poster_client&.client_sex %></b>
	</div>
	<div><%= PosterClient.human_attribute_name("phone") %>: 
		<b><%= @user.poster_client&.phone %></b>
	</div>
	<div><%= PosterClient.human_attribute_name("card_number") %>: 
		<b><%= @user.poster_client&.card_number %></b>
	</div>
<!-- 	<div><%= PosterClient.human_attribute_name("client_groups_id_client") %>: 
		<b><%= @user.poster_client&.client_groups_id_client %></b>
	</div> -->
	<div><%= PosterClient.human_attribute_name("country") %>: 
		<b><%= @user.poster_client&.country %></b>
	</div>
	<div><%= PosterClient.human_attribute_name("city") %>: 
		<b><%= @user.poster_client&.city %></b>
	</div>
	<div><%= PosterClient.human_attribute_name("birthday") %>: 
		<b><%= @user.poster_client&.birthday&.strftime('%d.%m.%Y') %></b>
	</div>
	<div><%= PosterClient.human_attribute_name("created_at") %>: 
		<b><%= @user.poster_client&.created_at&.strftime('%d.%m.%Y %T') %></b>
	</div>
	<div><%= PosterClient.human_attribute_name("updated_at") %>: 
		<b><%= @user.poster_client&.updated_at&.strftime('%d.%m.%Y %T') %></b>
	</div>
	<div><%= PosterClient.human_attribute_name("has_bonus") %>: 
		<b><%= @user.poster_client&.has_bonus ? "Да" : "Нет" %></b>
	</div>
	<div><%= PosterClient.human_attribute_name("bonus_updated_at") %>: 
		<b><%= @user.poster_client&.bonus_updated_at&.strftime('%d.%m.%Y %T') %></b>
	</div>
	<div><%= PosterClient.human_attribute_name("bonus_text") %>:</div> 
	<div><%= @user.poster_client&.bonus_text %></div>
</div>

app/views/static_pages/users_index_adm.html.erb
<% provide(:breadcrumb, "Админка / Пользователи") %>
<h2>Пользователи</h2>
<div class="form-group">
	<a class="btn btn-default" href="/admin">В админку</a>
</div>
<table class="table table-condensed" style="table-layout : fixed" width="100%">
	<thead>
		<tr>
			<th width="7%"><%= User.human_attribute_name("id") %></th>
			<th width="13%"><%= User.human_attribute_name("created_at") %></th>
			<th width="20%"><%= User.human_attribute_name("email") %></th>
			<th width="20%"><%= User.human_attribute_name("is_admin") %></th>
			<th width="20%">Клиент постера</th>
			<th width="20%"><%= PosterClient.human_attribute_name("client_name") %></th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= link_to user.id, "/user_adm/#{user.id}" %></td>
			<td><%= user.created_at.strftime('%d.%m.%Y %T') %></td>
			<td><%= user.email %></td>
			<td><%= user.is_admin ? "Да" : "Нет" %></td>
			<td><%= user.poster_client ? "Да" : "Нет" %></td>
			<td><%= user.poster_client&.client_name %></td>
		</tr>
		<% end %>
	</tbody>
</table>