config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'
  get '/admin', to: 'static_pages#admin'
  get '/test_payment', to: 'static_pages#test_payment'
  get '/news', to: 'static_pages#news'
  get '/users_index_adm', to: 'static_pages#users_index_adm'
  get 'user_adm/:id', to: 'static_pages#user_adm'

  resources :products
  get '/main', to: 'products#index_main'
  get '/foodtrack', to: 'products#index_foodtrack'
  get '/delivery', to: 'products#index_delivery'
  get '/delivery_products', to: 'products#index_delivery_products'
  get '/products_index_adm', to: 'products#index_adm'

  resources :poster_clients, only: [:new, :create, :edit, :update]
  get '/poster_info', to: 'poster_clients#poster_info'
  get '/bonus_info', to: 'poster_clients#bonus_info'
  get '/coupon', to: 'poster_clients#coupon'

  resources :poster_admin, only: [:index]
  post '/update_clients_bonus', to: 'poster_admin#update_clients_bonus'
  post '/update_poster_products', to: 'poster_admin#update_poster_products'

  # Yandex.Kassa
  post '/order_check', to: 'yandex_kassa#order_check'
  post '/order_payment_aviso', to: 'yandex_kassa#order_payment_aviso'
  get '/order_fail', to: 'yandex_kassa#order_fail'
  get '/order_success', to: 'yandex_kassa#order_success'

  # Shopping Cart
  resources :order_items, only: [:create, :update, :destroy]
  get '/cart', to: 'orders#cart'
  get '/order_placed', to: 'orders#order_placed'
  # get '/card_pay', to: 'orders#card_pay'
  resources :orders, only: [:update, :index, :show ]
  get "card_pay/:id", :controller => "orders", :action => "card_pay"
  get '/orders_index_adm', to: 'orders#index_adm'

end

app/controllers/poster_admin_controller.rb
class PosterAdminController < ApplicationController
  before_action :authenticate_admin
  
  def index
    @rinfo = Resque.info
    @resque_not_working = @rinfo[:workers] == 0 ? true : false
    @last_products_update_date = PosterProduct.last&.created_at&.strftime('%d.%m.%Y %T')
    @last_bonus_update_date = PosterClient.last&.bonus_updated_at&.strftime('%d.%m.%Y %T')
  end

  def update_clients_bonus
  	@clients = PosterClient.where("is_active = 't'").order(:id)
  	Rails.logger.info("PosterAdminController update_clients_bonus clients to update #{@clients.count}")
  	@clients.each do |client|
  		Resque.enqueue(UpdateClientsBonus, client.poster_client_id, nil)
  	end
    flash[:notice] = t(:update_clients_bonus_started)
    redirect_to poster_admin_index_path
  end

  def update_poster_products
    Rails.logger.info("PosterAdminController update_poster_products")
    Resque.enqueue(UpdatePosterProducts)
    flash[:notice] = t(:update_poster_products_started)
    redirect_to poster_admin_index_path
  end

end

app/views/poster_admin/index.html.erb
<% provide(:breadcrumb, "Админка / Интеграция с Poster") %>
<h2>Админка интеграции с Poster</h2>
<div class="poster_admin_index">
  <div class = "header-button">
    <a class="btn btn-default" href="/admin">В админку</a>
  </div>
  <br/>
  <h4>Обновить товары из Poster</h4>
  <div><b>Дата обновления товаров</b>: <br/> <%= @last_products_update_date %></div>
  <br/>
  <%= form_tag(update_poster_products_path, method: 'post') do %>
    <p><%= submit_tag('Обновить товары', class: 'btn btn-primary') %></p>
  <% end %>
  <br/>
  <h4>Обновить бонусы для всех клиентов</h4>
  <div><b>Дата обновления бонусов (по последней записи)</b>: <br/> <%= @last_bonus_update_date %></div>
  <br/>
  <%= form_tag(update_clients_bonus_path, method: 'post') do %>
    <p><%= submit_tag('Обновить бонусы', class: 'btn btn-primary') %></p>
  <% end %>
  <br/>
  <h4>Информация об очереди</h4>
  <% if @resque_not_working %>
    <div class="resque_not_working">
      Процесс для обработки заданий на сервере не запущен. Обратитесь к администратору info@busation.com
    </div>
  <% end %>
  <div>
    <%= @rinfo %>
  </div>
</div>