config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'
  get '/admin', to: 'static_pages#admin'
  get '/test_payment', to: 'static_pages#test_payment'
  get '/news', to: 'static_pages#news'
  get '/users_index_adm', to: 'static_pages#users_index_adm'
  get 'user_adm/:id', to: 'static_pages#user_adm'

  resources :products
  get '/main', to: 'products#index_main'
  get '/foodtrack', to: 'products#index_foodtrack'
  get '/delivery', to: 'products#index_delivery'
  get '/delivery_products', to: 'products#index_delivery_products'
  get '/products_index_adm', to: 'products#index_adm'

  resources :poster_clients, only: [:new, :create, :edit, :update]
  get '/poster_info', to: 'poster_clients#poster_info'
  get '/bonus_info', to: 'poster_clients#bonus_info'
  get '/coupon', to: 'poster_clients#coupon'

  resources :poster_admin, only: [:index]
  post '/update_clients_bonus', to: 'poster_admin#update_clients_bonus'
  post '/update_poster_products', to: 'poster_admin#update_poster_products'

  # Yandex.Kassa
  post '/order_check', to: 'yandex_kassa#order_check'
  post '/order_payment_aviso', to: 'yandex_kassa#order_payment_aviso'
  get '/order_fail', to: 'yandex_kassa#order_fail'
  get '/order_success', to: 'yandex_kassa#order_success'

  # Shopping Cart
  resources :order_items, only: [:create, :update, :destroy]
  get '/cart', to: 'orders#cart'
  get '/order_placed', to: 'orders#order_placed'
  # get '/card_pay', to: 'orders#card_pay'
  resources :orders, only: [:update, :index, :show ]
  get "card_pay/:id", :controller => "orders", :action => "card_pay"
  get '/orders_index_adm', to: 'orders#index_adm'

end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :img, ImgUploader
  belongs_to :category
  validates :category_id, presence: true
  validates :price, presence: true
  has_many :order_items
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin, only: [:index_adm, :new, :create, :edit, :update, :destroy]

  # PUBLIC PAGES
  def index
    # @products = Product.all
  end

  def index_main
    @products = Product.where("is_main = 't'").order(:id)
    @menu_name = t(:menu_name_main)
    render 'index_filtered'
  end

  def index_foodtrack
  	@products = Product.where("is_foodtrack = 't'").order(:id)
    @menu_name = t(:menu_name_foodtrack)
    render 'index_filtered'
  end

  def index_delivery
    all_categories = Category.all.order(:order)
    @categories = all_categories.select { |cat| cat if cat.products.count > 0 }
  end

  def index_delivery_products
    category_id = params[:category_id]
    @category = Category.where("id = #{category_id}").first
    @products = Product.where("is_foodtrack = 't' and category_id = #{category_id}").order(:id)
    @order_item = current_order.order_items.new
  end

  def show
    @product = Product.find(params[:id])  
  end

  # ADMIN PAGES
  def index_adm
    @products = Product.order(id: :desc)
    # self.index
    # render template: "products/index_adm" 
  end

  def new
    @product = Product.new
    @product.is_main = true
    @product.is_delivery = true
    @product.is_foodtrack = true
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = t(:product_saved_successfuly)
      # redirect_to edit_product_path @product
      redirect_to products_index_adm_path
    else
      render 'new'
    end  
  end

  def edit
    @product=Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
    	flash[:notice] = t(:product_saved_successfuly)
    	# redirect_to edit_product_path @product
      redirect_to products_index_adm_path
    else
    	render 'edit'
    end
  end

  def destroy
    @product=Product.find(params[:id])
    @product.destroy
    flash[:notice] = t(:product_deleted_successfuly)
    redirect_to products_index_adm_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :volume, :is_delivery, :is_foodtrack, 
      :img, :img_cache, :remove_img, :is_main, :category_id)
  end  
end

app/views/products/_edit_productimg.html.erb
<% img_has_errors = @product.errors[:img].present? %>
<% err_class_form_group = img_has_errors ? "has-error".html_safe : "".html_safe %>
<% err_class_label = img_has_errors ? "error".html_safe : "".html_safe %>
<div class="form-group optional product_img <%= err_class_form_group %>">	
  <label class="optional <%= err_class_label %>" for="product_img">
    <b>Изображение продукта</b>
  </label>
  <% if @product.img? %>
    <div>  
      <%= link_to(@product.img_identifier, @product.img.url)%>
      <label class="string optional checkbox inline" for="product_remove_img" style="font-weight: initial;">
        Удалить файл
        <%= f.check_box :remove_img %>
      </label>
    </div>
  <% end %>
  <%= f.file_field :img %>
  <%= f.hidden_field :img_cache %>
  <% if img_has_errors %>
    <span class="help-block"><%= @product.errors[:img].first %></span>
  <% end %>
</div>

app/views/products/_form.html.erb
<div>
	<div class="form-group">
		<a class="btn btn-default" href="/admin">В админку</a>
		<%= link_to "Список товаров", products_index_adm_path, class: "btn btn-default" %>
	</div>
	<div class="form-cont">
		<%= simple_form_for(@product, html: { class: 'form-horizontal' }) do |f| %>
		  <%= f.input :name %>
		  <%= f.input :category_id, collection: Category.order(:order).all, label_method: :name, value_method: :id %>
		  <%= f.input :description %>
		  <%= f.input :price %>
		  <%= f.input :volume %>
		  <%= f.input :is_main %>
		  <%= f.input :is_delivery %>
		  <%= f.input :is_foodtrack %>
		  <%= render 'edit_productimg', f: f %>
		  <div class="form-actions">
		    <%= button_tag "Сохранить", data: { disable_with: "Идет сохранение.." }, class: "btn btn-primary" %>
		  </div>
		<% end %>
	</div>
</div>

app/views/products/_modal_product_in_cart.html.erb
<!-- Modal -->
<div class="modal fade" id="productInCart" tabindex="-1" role="dialog" aria-labelledby="productInCartLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="productInCartLabel">Товар добавлен в корзину</h4>
      </div>
      <div class="modal-body">
        <div class="link_to_cart"><a href="/cart">Перейти в корзину</a></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>

app/views/products/_product_row.html.erb
<div class="thumbnail">
  <%= image_tag product.img.url %>
  <h5><%= product.name %> - <%= product.price %> руб.</h5>
  <h5><small><%= product.description %></small></h5>
  <%= simple_form_for order_item, remote: true do |f| %>
  <%= f.hidden_field :product_id, value: product.id %>
  <%= f.input :quantity, label: false, input_html: {value: '1'} %>
  <div class="form-group order_item_button">
    <%= f.button :submit, value: "+", data: { disable_with: "+" }, class: "btn btn-primary" %>
  </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<% provide(:breadcrumb, "Админка / Редактирование товара") %>
<h2>Редактирование товара</h2>
<%= render "form" %>

app/views/products/index.html.erb
<ul>
    <li><%= link_to 'Доставка', '/delivery' %></li>
    <li><%= link_to 'Основное меню', '/main' %></li>
    <li><%= link_to 'Фудтрак', '/foodtrack' %></li>
</ul>

app/views/products/index_adm.html.erb
<% provide(:breadcrumb, "Админка / Список товаров") %>
<h2>Список товаров</h2>
<div>
  <div class = "header-button">
    <a class="btn btn-default" href="/admin">В админку</a>
    <%= link_to "Создать", new_product_path, class: "btn btn-primary" %>
  </div>
  <table class="table table-bordered">
      <thead>
        <tr>
          <th></th>
          <th><%= Product.human_attribute_name(:name) %></th>
          <th><%= Product.human_attribute_name(:category_id) %></th>
          <th><%= Product.human_attribute_name(:price) %></th>
          <th><%= Product.human_attribute_name(:is_delivery) %></th>
          <th><%= Product.human_attribute_name(:updated_at) %></th>
          <th><%= Product.human_attribute_name(:img) %></th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |prod| %>
          <tr>
            <td>
              <div class="btn-cont"><%= link_to "Изменить", edit_product_path(prod), class: "btn-sm btn-primary" %></div>
              <div class="btn-cont"><%= link_to "Просмотр", product_path(prod), class: "btn-sm btn-primary" %></div>
              <div class="btn-cont"><%= link_to "Удалить", product_path(prod), class: "btn-sm btn-danger",method: "delete" %></div>
            <td><%= prod.name %></td>
            <td><%= prod.category&.name %></td>
            <td><%= prod.price %></td>
            <td><%= prod.is_delivery %></td>
            <td><%= prod.updated_at.strftime('%d.%m.%Y %T') %></td>
            <td>
              <%= image_tag(prod.img.url, class: 'grid-img') if !prod.img.blank? %>
            </td>
          </tr>
        <% end %>
      </tbody>
  </table>
</div>

app/views/products/index_delivery.html.erb
<%= render 'modal_product_in_cart' %>
<main class="page-content">
  <section class="section-md-top-20 position-r bg-images-5 bg-images-category">
    <div class="shell text-center text-md-left products_delivery_block">
      <h3>Доставка</h3>
      <%= render 'layouts/cart_text' %>
      <div class="range">
        <% @categories.each_with_index do |category, index| %>
        <div class="cell-md-3 cell-xs-6 category">
          <div class="thumbnail">
            <%= deilvery_products_by_category_link_to category_image_tag(category.code), category.id %>
            <h5><%= deilvery_products_by_category_link_to category.name, category.id %></h5>
          </div>
        </div>
        <% if (index%3 == 2) %>
        <div class="cell-md-1 display-n"></div>
        <% end %>
        <% end %>
      </div>
    </div>
  </section>
</main>

app/views/products/index_delivery_products.html.erb
<%= render 'modal_product_in_cart' %>
<main class="page-content">
	<section class="section-md-top-20 position-r bg-images-5 bg-images-main">
		<div class="shell text-center text-md-left products_delivery_block">
			<h3>Доставка - <%= @category.name %></h3>
			<%= render 'layouts/cart_text' %>
			<div class="range">
				<% @products.each_with_index do |prod, index| %>
					<div class="cell-md-3 cell-xs-6 product">
						<%= render "product_row", product: prod, order_item: @order_item %>
					</div>
					<% if (index%3 == 2) %>
						<div class="cell-md-1 display-n"></div>
					<% end %>
				<% end %>
			</div>
		</div>
	</section>
</main>

app/views/products/index_filtered.html.erb
<main class="page-content">
	<section class="section-md-top-20 position-r bg-images-5 bg-images-main">
		<div class="shell text-center text-md-left products_block">
			<h3><%= @menu_name %></h3>
			<div class="range">
				<% @products.each_with_index do |prod, index| %>
					<div class="cell-md-3 cell-xs-6 product">
						<div class="thumbnail">
							<%= image_tag prod.img.url %>
							<h5><%= prod.name %> - <%= prod.price %> руб.</h5>
							<h5><small><%= prod.description %></small></h5>
						</div>
					</div>
					<% if (index%3 == 2) %>
						<div class="cell-md-1 display-n"></div>
					<% end %>
				<% end %>
			</div>
		</div>
	</section>
</main>

app/views/products/new.html.erb
<% provide(:breadcrumb, "Админка / Создание товара") %>
<h2>Создание товара</h2>
<%= render "form" %>

app/views/products/show.html.erb
<% provide(:title, @product.name) %>
<% provide(:keywords, @product.name)%>
<% provide(:description, @product.name) %>
<div class="row">
  <div class="col-md-12">
  	<% if true %>
      <div class="form-group">
        <a class="btn btn-default" href="/admin">В админку</a>
        <%= link_to "Список товаров", products_index_adm_path, class: "btn btn-default" %>
  	    <%= link_to "Редактировать", edit_product_path(@product), class: "btn btn-primary" %>
      </div>
  	<% end %>
  	<h1><%= @product.name %></h1>
    <p><%= @product.description %></p>
    <%= image_tag @product.img.url %>
  </div>
</div>