config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'
  get '/admin', to: 'static_pages#admin'
  get '/test_payment', to: 'static_pages#test_payment'
  get '/news', to: 'static_pages#news'
  get '/users_index_adm', to: 'static_pages#users_index_adm'
  get 'user_adm/:id', to: 'static_pages#user_adm'

  resources :products
  get '/main', to: 'products#index_main'
  get '/foodtrack', to: 'products#index_foodtrack'
  get '/delivery', to: 'products#index_delivery'
  get '/delivery_products', to: 'products#index_delivery_products'
  get '/products_index_adm', to: 'products#index_adm'

  resources :poster_clients, only: [:new, :create, :edit, :update]
  get '/poster_info', to: 'poster_clients#poster_info'
  get '/bonus_info', to: 'poster_clients#bonus_info'
  get '/coupon', to: 'poster_clients#coupon'

  resources :poster_admin, only: [:index]
  post '/update_clients_bonus', to: 'poster_admin#update_clients_bonus'
  post '/update_poster_products', to: 'poster_admin#update_poster_products'

  # Yandex.Kassa
  post '/order_check', to: 'yandex_kassa#order_check'
  post '/order_payment_aviso', to: 'yandex_kassa#order_payment_aviso'
  get '/order_fail', to: 'yandex_kassa#order_fail'
  get '/order_success', to: 'yandex_kassa#order_success'

  # Shopping Cart
  resources :order_items, only: [:create, :update, :destroy]
  get '/cart', to: 'orders#cart'
  get '/order_placed', to: 'orders#order_placed'
  # get '/card_pay', to: 'orders#card_pay'
  resources :orders, only: [:update, :index, :show ]
  get "card_pay/:id", :controller => "orders", :action => "card_pay"
  get '/orders_index_adm', to: 'orders#index_adm'

end

app/views/layouts/_cart_text.html.erb
<div class="cart-text">
	<%= link_to "ВАШ ЗАКАЗ (#{current_order.order_items.size})", '/cart', class: "btn btn-link" %>
</div>

app/views/layouts/_footer.html.erb
  <footer class="page-foot section-80 section-lg-120">
    <div class="shell">
      <div class="range">
        <div class="cell-md-3 cell-sm-4 cell-md-push-2">
          <div class="contact-info text-center text-sm-left">
            <p>Москва,<br class="hidden visible-lg-block visible-md-block">ул. Волочаевская, д.38, стр.1</p>
          </div>
        </div>
        <div class="cell-md-3 cell-sm-4 text-center text-sm-left cell-md-push-3"><span class="material-icons-local_phone icon icon-xs"></span><span class="phone"><a href="callto:#" class="text-bold">(800) 123 1234</a></span></div>
        <div class="cell-md-2 cell-sm-4 cell-md-preffix-1 text-center text-sm-left cell-md-push-4">
          <ul class="list-inline">
            <li><a href="#" class="fa-facebook"></a></li>
            <li><a href="#" class="fa-google-plus"></a></li>
            <li><a href="#" class="fa-linkedin"></a></li>
            <li><a href="#" class="fa-twitter"></a></li>
          </ul>
        </div>
        <div class="cell-md-3 text-center text-md-left cell-md-push-1">
          <div class="brand"><a href="index.html">MITRO FOOD</a></div>
          <p class="offset-top-10">&#169;<span id="copyright-year"></span>
          </p>
        </div>
      </div>
    </div>
  </footer>
<%= javascript_include_tag 'core.min' %>
<%= javascript_include_tag 'script' %>

app/views/layouts/_head.html.erb
<head>
    <title><%= content_for?(:title) ? yield(:title) : t(:default_title) %></title>  
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : t(:default_title) %>">
    <meta name="keywords" content="<%= content_for?(:keywords) ? yield(:keywords) : t(:default_title) %>">
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <link rel="icon" href="<%= asset_path 'favicon.ico' %>" type="image/x-icon">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Montserrat:400,700%7CMerriweather:400,300,300italic,400italic,700,700italic,900italic,900">
</head>

app/views/layouts/_messages.html.erb
<% if notice %>
<div class="alert alert-info notice alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= notice %>
</div>
<% end %>
<% if alert %>
<div class="alert alert-danger alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= alert %>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="rd-navbar-wrap">
  <nav data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-static" data-md-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-static" data-lg-device-layout="rd-navbar-static" data-sm-stick-up-offset="50px" data-lg-stick-up-offset="150px" class="rd-navbar">
    <div class="rd-navbar-inner">
      <!-- RD Navbar Panel-->
      <div class="rd-navbar-panel">
        <!-- RD Navbar Toggle-->
        <button data-rd-navbar-toggle=".rd-navbar-nav-wrap" class="rd-navbar-toggle"><span></span></button>
        <!-- RD Navbar Brand-->
        <div class="rd-navbar-brand"><a href="/" class="brand-name">MITRO FOOD<br><span class="brand-slogan">Лучший кофе</span></a></div>
      </div>
      <div class="rd-navbar-nav-wrap">
        <!-- RD Navbar Nav-->
        <ul class="rd-navbar-nav">
          <li><a href="/">главная</a></li>
          <li><a href='/main'>меню</a>
            <!-- RD Navbar Dropdown-->
            <ul class="rd-navbar-dropdown">
              <li><a href="/main">Основное меню</a>
              </li>
              <li><a href="/foodtrack">Фудтрак</a></li>
            </ul>
          </li>
          <li><a href='/delivery'>доставка</a></li>
          <li><a href='/news'>новости</a></li>
          <% if user_signed_in? %>
            <li><a href='#'>ЛК меню</a>
              <ul class="rd-navbar-dropdown">
                <% if current_user.is_admin? %>
                  <li><%= link_to 'Админка', admin_path %></li>
                  <li><%= link_to 'Товары', products_index_adm_path %></li>
                <% else %>
                  <li><%= link_to 'Бонусная карта', new_poster_client_path %></li>
                  <li><%= link_to 'Мои бонусы', bonus_info_path %></li>
                <% end %>
                <li><%= link_to 'Выход', destroy_user_session_path, method: 'delete' %></li>
              </ul>
            </li>
          <% else %>
            <li><a href='/users/sign_in'>ЛК вход</a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <header class="page-head section-sm-50 section-lg-top-90 section-lg-bottom-80 bg-images-1">
      <!-- RD Navbar-->
      <%= render 'layouts/navigation' %>
    </header>
    <div class="container">
      <div class='nav-breadcrumbs'><span><%= yield(:breadcrumb)%></span></div>
    </div>
    <div class="container">
      <%= render 'layouts/messages' %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/application_home.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
  	<div class="home_messages_container">
      <%= render 'layouts/messages' %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/application_pages.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <header class="page-head section-sm-50 section-lg-top-90 section-lg-bottom-80 bg-images-1">
      <!-- RD Navbar-->
      <%= render 'layouts/navigation' %>
    </header>
    <div class="container">
      <div class='nav-breadcrumbs'><span><%= yield(:breadcrumb)%></span></div>
    </div>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/coupon_layout.html.erb
<!DOCTYPE html>
<html>
	<head>
	    <title>Купон MITROFOOD</title>  
	    <meta charset="utf-8">
	    <%= stylesheet_link_tag    'coupon', media: 'all' %>
	</head>
  <body>
    <%= yield %>
  </body>
</html>